# Generated by Django 4.0.2 on 2022-02-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_todo_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='priority',
            field=models.CharField(choices=[('0', 'Low'), ('1', 'Medium'), ('2', 'High')], default='0', max_length=2),
        ),
    ]
