# Generated by Django 4.0.2 on 2022-02-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_todoitem_done_alter_todoitem_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='due_by',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
